-- // Settings, initialized by KingCreoo on 8-19-2025
-- // Holds all basic game data

local SETTINGS = {}

SETTINGS.DEFAULT_DATA = {
    ["leaderstats"] = {
        ["Credits"] = 100
    },
    ["Plot"] = {
        ["Unlocks"] = {
            ["Slot1"] = true,
            ["Slot2"] = true,
            ["Slot3"] = false,
            ["Slot4"] = false,
            ["Slot5"] = false,
            ["Slot6"] = false,
            ["Slot7"] = false
        }
    },
    ["Inventory"] = {
        ["ActiveSoldiers"] = {},
        ["SoldierInventory"] = {},
        ["ActiveTarget"] = "Target1",
        ["TargetInventory"] = {["Target1"] = true},
    },
    ["Settings"] = {
        ["AutoEquip"] = false,
        ["PotatoMode"] = true
    }
}

SETTINGS.SOLDIER_DATA = {
    ["The Grunt"] = {
        ["FireRate"] = 4,
        ["Damage"] = 1,
        ["BulletSpeed"] = 40,
        ["Price"] = 10,
        ["RobuxPrice"] = 3,
        ["Rarity"] = 1,
        ["Image"] = "rbxassetid://73900105861068",
        ["Color"] = Color3.fromRGB(72, 157, 236),
        ["Weapon"] = "M4"
    },
    ["The Shotgunner"] = {
        ["FireRate"] = 4,
        ["Damage"] = 1,
        ["BulletSpeed"] = 40,
        ["Price"] = 25,
        ["RobuxPrice"] = 5,
        ["Rarity"] = 1,
        ["Image"] = "rbxassetid://73900105861068",
        ["Color"] = Color3.fromRGB(72, 157, 236),
        ["Weapon"] = "Pump"
    },
    ["The Heavy"] = {
        ["FireRate"] = 4,
        ["Damage"] = 1,
        ["BulletSpeed"] = 40,
        ["Price"] = 60,
        ["RobuxPrice"] = 10,
        ["Rarity"] = .9,
        ["Image"] = "rbxassetid://73900105861068",
        ["Color"] = Color3.fromRGB(72, 157, 236),
        ["Weapon"] = "LMG"
    }
}

SETTINGS.SHOP_ORDER = {"The Grunt", "The Shotgunner", "The Heavy"}

SETTINGS.RATING_ORDER = {"The Heavy", "The Shotgunner", "The Grunt"}

SETTINGS.WEAPON_DATA = {
    ["M4"] = {
        ["C0"] = CFrame.new(-0.697, -2.093, 0.167) * CFrame.Angles(math.rad(-90), 0, 0),
        ["C1"] = CFrame.new(0, -0.062, -0.489),
        ["FireOffset"] = Vector3.new(4.5, 1.6, 0.4)
    }
}

SETTINGS.TARGET_DATA = {
    ["Target1"] = {
        ["TotalHealth"] = 3,
        ["TotalRespawnTime"] = 2,
        ["Reward"] = 3,
        ["Color"] = Color3.fromRGB(255, 66, 66)
    },
    ["Target2"] = {
        ["TotalHealth"] = 5,
        ["TotalRespawnTime"] = 1.8,
        ["Reward"] = 10,
        ["Color"] = Color3.fromRGB(255, 66, 66)
    },
    ["Target3"] = {
        ["TotalHealth"] = 10,
        ["TotalRespawnTime"] = 1.7,
        ["Reward"] = 25,
        ["Color"] = Color3.fromRGB(255, 66, 66)
    }
}

SETTINGS.DISTANCES = {
    ["Worlds"] = {
        ["Default"] = 55,
    }
}

return SETTINGS